### PR TITLE
Dynamic Achievement System (Not Tested)

### PR DESCRIPTION
**Pull request by Serializator**
This PR is meant to make the achievement storing system dynamic, I didn't test it because I don't have enough time to setup the MySQL database for it, sorry for that.

### CODE REVIEW

**Comment by eliblaney** [comment]
This is great, exactly what I was thinking when I commented on SgtCaze's video.

**Comment by sgtcaze** [comment]
Looking sweet. I'll test some this out in our next demonstration video.

**Comment by Serializator** [comment]
I know it looks sweet, I almost ate while making it!

**Comment by sgtcaze** [comment]
I changed up your code as I could not compile it (I know it was untested)

I believe this may be a more straightforward way of accomplishing dynamic achievements.

https://github.com/sgtcaze/ZombieEscape/blob/master/src/main/java/net/cosmosmc/mcze/profiles/ProfileLoader.java#L75

**Comment by Serializator** [comment]
If it works for you it probably is ;-)

**Pull request merged**
