### PR TITLE
Quickly changed all the variables that can be final to final and rena…

### PR DESCRIPTION
**Pull request by Serializator**
…med them so they use the Java naming convention.

### CODE REVIEW

**Comment by Serializator** [comment]
No problem.

**Comment by Serializator** [comment]
When I imported the project into IntelliJ IDEA and looked at the pom.xml and there where a couple of problems.
- There has never been a org.bukkit.bukkit.1.8.8-R0.1-SNAPSHOT dependency in the bukkit-repo, how did you get it to work? If you manually added the dependency in your .m2 folder there is a chance people can't get it to work at all because they don't know what's going on.
- The same problem with the org.bukkit.craftbukkit.1.8.8-R0.1-SNAPSHOT dependency in the bukkit-repo repository.
- The fanciful-mvn-repo is offline, it can be that the mkremins.fanciful.0.3.3-SNAPSHOT dependency is cached in your .m2 folder, but people who never used the dependency before don't have it, or you also added the dependency manually in your .m2 folder.

Hope the explanation isn't to confusing, and hopefully I'm not the person who looks dumb because the answer is to simple that a toddler could fix it ;-P

**Comment by sgtcaze** [comment]
No worries man! A subscriber pointed about some dependency concerns. I'll add some more information and resolve some things.

**Comment by Serializator** [comment]
You're the best ;-)

**Pull request merged**
